import Image from "next/image";
import { ArrowUpRight, ArrowDown, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import Navigation from "./Navigation";
import DeliveryDiagram from "./DeliveryDiagram";
import Footer from "./Footer";
import { references } from "../data/references";

const pillars = [["Gouvernance", "Clarifier les responsabilités, les décisions, les engagements et les mécanismes d’escalade."], ["Delivery", "Structurer les roadmaps, les dépendances, les capacités, les risques et les engagements de programme."], ["Transformation", "Faire évoluer l’organisation, les processus et les modes de fonctionnement qui limitent la capacité à livrer."], ["Intelligence & Automation", "Exploiter Jira, Confluence, la data et l’IA pour automatiser le reporting, détecter les risques et améliorer la qualité des décisions."]];
const steps = [["Diagnose", "Comprendre les objectifs, les acteurs, les flux de décision, les contraintes, les dépendances et les sources de friction."], ["Structure", "Définir la gouvernance, les responsabilités, les mécanismes de delivery et les indicateurs."], ["Operate", "Faire fonctionner le système avec les équipes et sécuriser les engagements."], ["Automate", "Automatiser progressivement le reporting, la détection des risques, la consolidation des données et la préparation des décisions."]];
const problems = ["Une roadmap ambitieuse, une capacité réelle difficile à évaluer.", "Des dizaines de dépendances entre équipes.", "Des comités et des réunions qui se multiplient.", "Des responsabilités floues entre métier, IT et fournisseurs.", "Un pilotage fondé sur l’activité plutôt que sur les résultats.", "Des données dispersées entre Jira, Confluence, Excel et les outils PPM."];
const outcomes = ["Des engagements plus explicites", "Des dépendances visibles", "Des arbitrages plus rapides", "Des risques détectés plus tôt", "Une meilleure prévisibilité", "Moins de reporting manuel", "Des données de delivery mieux exploitées", "Un management concentré sur les décisions"];
const faqs = [
  ["NEATCH est-il une agence ou une ESN ?", "Non. Je pilote personnellement les interventions NEATCH. Selon les besoins du programme, je réunis et j’organise des consultants d’ESN et des freelances issus de Malt, d’autres plateformes ou de mon réseau. Je clarifie leurs responsabilités, coordonne leurs contributions et structure un cadre de delivery commun."],
  ["Comment travaillez-vous avec les ESN et les plateformes de freelances ?", "Je m’appuie sur cet écosystème pour identifier les compétences adaptées au programme. Je qualifie les profils en fonction du contexte, puis j’organise leur contribution avec les équipes métier et IT. Les ESN, Malt et les autres plateformes restent des partenaires du dispositif."],
  ["Quand faire appel à NEATCH ?", "Lorsque votre programme implique plusieurs équipes et fournisseurs, des responsabilités fragmentées et des dépendances difficiles à piloter. Nous intervenons auprès des grandes entreprises et ETI pour structurer une capacité de delivery alignée avec les objectifs métier."],
  ["Quel est votre périmètre d’intervention ?", "La gouvernance, l’architecture du delivery et la transformation de l’organisation : responsabilités, capacités, dépendances, engagements, risques et arbitrages. Nous travaillons avec les équipes métier, IT, architecture et les intégrateurs."],
  ["Quelle place donnez-vous à l’IA ?", "L’IA est intégrée progressivement pour consolider le reporting, exploiter la connaissance projet, repérer les risques et préparer les décisions. Les usages dépendent de la qualité des données, des droits d’accès et des règles de confidentialité. Les décisions restent sous responsabilité humaine."],
  ["Comment démarre une collaboration ?", "Un premier échange permet de comprendre vos objectifs, vos acteurs, vos contraintes et les points de friction. Nous définissons ensuite un diagnostic, un périmètre d’intervention et des résultats attendus, avec des indicateurs adaptés au contexte."]
];
function Heading({ number, label, title, children }: { number: string; label: string; title: string; children?: React.ReactNode }) {
  return <div className="mb-10 grid gap-6 lg:grid-cols-2 lg:gap-16"><div><p className="mb-4 font-mono text-xs text-muted-foreground"><span className="mr-3 inline-block h-2 w-2 rounded-full bg-brand" aria-hidden="true" />{number} / {label}</p><h2 className="text-3xl font-semibold tracking-tight md:text-4xl">{title}</h2></div>{children && <p className="self-end leading-7 text-muted-foreground">{children}</p>}</div>;
}
const section = "mx-auto max-w-6xl px-6 py-20 md:py-28";
function Tiles({ items }: { items: string[][] }) {
  return <div className="grid gap-4 sm:grid-cols-2">{items.map(([title, text], index) => <Card key={title}><CardHeader><p className="mb-4 font-mono text-xs text-muted-foreground">0{index + 1}</p><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-7 text-muted-foreground">{text}</p></CardContent></Card>)}</div>;
}
export default function EditorialHome() {
  return <><Navigation /><main id="main-content" tabIndex={-1}>
    <section className="border-b" aria-labelledby="hero-title"><div className="mx-auto max-w-6xl px-6 pb-16 pt-8 md:pb-20 md:pt-12"><Badge variant="outline">Transformation &amp; Delivery</Badge><div className="mt-8 grid items-start gap-12 lg:grid-cols-[1.6fr_1fr] lg:gap-16"><div><h1 id="hero-title" className="text-4xl font-semibold leading-tight tracking-tight sm:text-5xl md:text-6xl">Piloter les transformations complexes.<br /><span className="text-brand">Livrer ce qui compte.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground">NEATCH prend en charge la gouvernance et le delivery de programmes de transformation complexes mêlant ERP, data, IA, intégration, équipes multiples et fournisseurs multiples.</p><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">Nous transformons la coordination en un système de delivery mesurable, prévisible et progressivement automatisé.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href="#contact">Discuter d’un programme <ArrowUpRight /></a></Button><Button asChild variant="outline"><a href="#methode">Découvrir notre approche <ArrowDown /></a></Button></div></div><Card><CardHeader><p className="mb-3 font-mono text-xs text-muted-foreground">DU PROGRAMME AU SYSTÈME</p><CardTitle>Une ambition. Des engagements.<br />Un système pilotable.</CardTitle></CardHeader><CardContent><DeliveryDiagram /><ul className="divide-y">{["Responsabilités clarifiées", "Dépendances visibles", "Décisions documentées", "Résultats mesurables"].map(item => <li key={item} className="flex items-center gap-3 py-4 text-sm"><Check className="size-4 shrink-0 text-brand" aria-hidden="true" />{item}</li>)}</ul><p className="mt-4 font-mono text-xs text-muted-foreground">Métier · IT · Équipes · Fournisseurs</p></CardContent></Card></div><div className="mt-16 flex flex-wrap justify-between gap-3 border-t pt-6 text-xs text-muted-foreground"><span>Gouvernance · Transformation · Delivery</span><span>Pour les DSI, CTO et directions de programme</span></div></div></section>
    <section className="border-b bg-muted/50" aria-label="Références du parcours de Lionel Sultan"><div className="mx-auto max-w-6xl px-6 py-10"><p className="font-mono text-xs text-muted-foreground">Des expériences dans des organisations exigeantes</p><ul className="mt-6 grid grid-cols-2 items-center gap-6 text-lg font-semibold tracking-tight sm:grid-cols-4"><li>Dior</li><li>CHANEL</li><li>EDF Renouvelables</li><li>BNP PARIBAS</li></ul></div></section>
    <section className={section} id="enjeux"><Heading number="01" label="Le constat" title="Quand le programme devient plus complexe que son organisation">Les équipes travaillent. Les réunions s’enchaînent. Mais la trajectoire et la capacité à livrer restent difficiles à lire.</Heading><ul className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{problems.map((item, index) => <li key={item} className="border-t pt-5"><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><p className="mt-3 leading-7">{item}</p></li>)}</ul><p className="mt-12 max-w-4xl border-l-2 border-brand pl-6 text-xl leading-8 tracking-tight">Le problème n’est généralement pas le manque d’activité. C’est l’absence d’un système de delivery suffisamment clair pour transformer cette activité en résultats prévisibles.</p></section>
    <section className="border-y bg-muted/50" id="principes"><div className={section}><Heading number="02" label="Notre proposition" title="Construire un véritable système de delivery">Transformer les organisations qui produisent beaucoup de coordination et de temps passé en systèmes de delivery mesurables, automatisés et pilotés par les résultats.</Heading><Tiles items={pillars} /></div></section>
    <section className={section} id="expertise"><Heading number="03" label="Expertise" title="Là où organisation, technologie et delivery se rencontrent">Relier les enjeux métier à la réalité des systèmes, des équipes et des fournisseurs. Notre rôle : la gouvernance, l’architecture du delivery et la transformation.</Heading><div className="flex flex-wrap gap-3">{["Program Delivery", "Transformation Operating Model", "ERP / SAP", "Supply Chain", "Data & Analytics", "Integration & APIs", "Cloud", "AI-enabled Delivery", "Product & Portfolio Governance"].map(item => <Badge key={item} variant="secondary">{item}</Badge>)}</div><p className="mt-8 max-w-3xl text-sm leading-7 text-muted-foreground">SAP transformation, data transformation, integration governance, supply chain transformation : des contextes différents, une même exigence de pilotage transverse.</p></section>
    <section className="border-y bg-muted/50" id="methode"><div className={section}><Heading number="04" label="Approche" title="De la situation complexe au système pilotable">Un delivery operating model adapté à votre programme, puis mis en œuvre avec les équipes.</Heading><div className="mx-auto max-w-2xl"><DeliveryDiagram variant="sequence" /></div><Tiles items={steps} /></div></section>
    <section className={section} id="ai-delivery"><Heading number="05" label="AI-enabled Delivery" title="L’IA, une couche opérationnelle du delivery">Synthèse automatique, analyse des risques, préparation de décisions, détection de dépendances, génération de reporting et exploitation de la connaissance projet.</Heading><div className="grid gap-4 md:grid-cols-3">{[["Automate reporting", "Consolider les données Jira, Confluence et PPM, synthétiser l’avancement et générer les supports de pilotage."], ["Surface risks and dependencies", "Faire émerger les signaux de risque, repérer les dépendances et exploiter la connaissance projet."], ["Augment decision-making", "Préparer les arbitrages, rendre les options lisibles et documenter les éléments utiles à la décision."]].map(([title, text], index) => <Card key={title}><CardHeader><DeliveryDiagram variant={(["reporting", "risks", "decisions"] as const)[index]} /><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-7 text-muted-foreground">{text}</p></CardContent></Card>)}</div><p className="mt-8 text-sm leading-7 text-muted-foreground">Une automatisation progressive, selon la qualité des sources, les droits d’accès et les règles de confidentialité du programme.</p></section>
    <section className="border-y bg-muted/50" id="resultats"><div className={section}><Heading number="06" label="Résultats attendus" title="Ce que doit produire une intervention NEATCH">Des changements observables dans la façon de piloter et de livrer. Les indicateurs et leur point de départ sont définis avec vous.</Heading><ul className="grid gap-x-12 sm:grid-cols-2">{outcomes.map(item => <li key={item} className="flex items-center gap-3 border-b py-5"><Check className="size-4 shrink-0 text-brand" aria-hidden="true" />{item}</li>)}</ul></div></section>
    <section className={section} id="about"><Heading number="07" label="À propos" title="Un cabinet indépendant. Une expérience de terrain." /><div className="grid gap-12 md:grid-cols-[1.5fr_1fr]"><div className="space-y-5 leading-7 text-muted-foreground"><p className="text-lg text-foreground">NEATCH est ma structure indépendante pour piloter la gouvernance et le delivery de transformations complexes.</p><p>Je ne suis pas une agence. Je réunis et j’organise les compétences nécessaires au programme : consultants d’ESN, freelances issus de Malt et d’autres plateformes, ainsi que de mon réseau.</p><p>Je reste votre interlocuteur pour qualifier les profils, clarifier les responsabilités et organiser leurs contributions dans un système de delivery commun.</p><p>Nous intervenons au croisement du métier, de l’IT, de l’architecture et des équipes de delivery pour transformer des programmes complexes en systèmes pilotables.</p><p>Nous travaillons avec les DSI, CIO, CTO, directions de programme et de transformation, responsables ERP, Data et Digital et directions Supply Chain et Operations.</p><p className="text-sm">Program Delivery Lead · Transformation Lead · Product &amp; Delivery Lead · Program Governance</p></div><Card><CardHeader><Image src="/lionel-sultan.png" alt="Lionel Sultan, fondateur de NEATCH" width={480} height={480} sizes="(max-width: 768px) 90vw, 360px" className="h-auto w-full rounded-md" /></CardHeader><CardContent><h3 className="font-semibold">Lionel Sultan</h3><p className="mt-1 text-sm text-muted-foreground">Fondateur · 15 ans d’expérience</p></CardContent></Card></div></section>
    <section className="border-y bg-muted/50" id="references"><div className={section}><Heading number="08" label="Références" title="Des programmes ancrés dans la réalité des organisations">Une sélection issue du parcours de Lionel Sultan, du luxe à l’énergie et aux services financiers.</Heading><Tiles items={[["Christian Dior Couture", "Orchestration du delivery multi-équipes, Product Management sur Merchandise Planning et pilotage d’un projet supply chain basé sur Anaplan."], ["EDF Renouvelables", "Pilotage de projets métier et terrain, évolutions d’une application de maintenance SAP et coordination de chantiers applicatifs et infrastructures."]]} /><div className="mt-8"><Accordion type="single" collapsible><AccordionItem value="library"><AccordionTrigger>Explorer toutes les références du parcours</AccordionTrigger><AccordionContent><Accordion type="single" collapsible>{references.map(reference => <AccordionItem value={`${reference.company}-${reference.period}`} key={`${reference.company}-${reference.period}`}><AccordionTrigger><span className="text-left">{reference.company}<span className="ml-3 text-xs font-normal text-muted-foreground">{reference.period}</span></span></AccordionTrigger><AccordionContent><h3 className="font-semibold">{reference.role}</h3><p className="mt-3 leading-7 text-muted-foreground">{reference.context}</p><div className="mt-6 grid gap-6 md:grid-cols-2">{[["Travaux clés", reference.assignments], ["Résultats de la mission", reference.outcomes]].map(([title, items]) => <div key={title as string}><h4 className="mb-3 font-medium">{title}</h4><ul className="list-disc space-y-2 pl-5 leading-6 text-muted-foreground">{(items as string[]).map(item => <li key={item}>{item}</li>)}</ul></div>)}</div></AccordionContent></AccordionItem>)}</Accordion></AccordionContent></AccordionItem></Accordion></div></div></section>
    <section className={section} id="faq"><Heading number="09" label="Questions fréquentes" title="Préciser le cadre d’intervention" /><Accordion type="single" collapsible>{faqs.map(([question, answer], index) => <AccordionItem value={String(index)} key={question}><AccordionTrigger className="text-left">{question}</AccordionTrigger><AccordionContent><p className="max-w-4xl leading-7 text-muted-foreground">{answer}</p></AccordionContent></AccordionItem>)}</Accordion></section>
    <section className="mx-auto max-w-6xl px-6 pb-20" id="contact"><Card><CardHeader><p className="mb-3 font-mono text-xs text-muted-foreground">10 / CONTACT</p><CardTitle>Votre transformation mérite un système de delivery clair.</CardTitle></CardHeader><CardContent><p className="max-w-2xl leading-7 text-muted-foreground">Un premier échange pour comprendre vos objectifs, vos dépendances et les décisions à sécuriser.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild><a href="mailto:contact@neatch.com">contact@neatch.com <ArrowUpRight /></a></Button><Button variant="outline" asChild><a href="https://www.linkedin.com/in/lionelsultan" target="_blank" rel="noopener noreferrer">Lionel Sultan sur LinkedIn <ArrowUpRight /><span className="sr-only"> (nouvel onglet)</span></a></Button></div></CardContent></Card></section>
  </main><Footer /></>;
}
