import Image from "next/image";
import { references } from "../data/references";

const links = [["#main-content", "Accueil"], ["#expertise", "Expertise"], ["#methode", "Approach"], ["#ai-delivery", "AI-enabled Delivery"], ["#about", "About"], ["#contact", "Contact"]];
const pillars = [["Gouvernance", "Clarifier les responsabilités, les décisions, les engagements et les mécanismes d’escalade."], ["Delivery", "Structurer les roadmaps, les dépendances, les capacités, les risques et les engagements de programme."], ["Transformation", "Faire évoluer l’organisation, les processus et les modes de fonctionnement qui limitent la capacité à livrer."], ["Intelligence & Automation", "Exploiter Jira, Confluence, la data et l’IA pour automatiser le reporting, détecter les risques et améliorer la qualité des décisions."]];
const steps = [["Diagnose", "Comprendre les objectifs, les acteurs, les flux de décision, les contraintes, les dépendances et les sources de friction."], ["Structure", "Définir la gouvernance, les responsabilités, les mécanismes de delivery et les indicateurs."], ["Operate", "Faire fonctionner le système avec les équipes et sécuriser les engagements."], ["Automate", "Automatiser progressivement le reporting, la détection des risques, la consolidation des données et la préparation des décisions."]];
const problems = ["Une roadmap ambitieuse, une capacité réelle difficile à évaluer.", "Des dizaines de dépendances entre équipes.", "Des comités et des réunions qui se multiplient.", "Des responsabilités floues entre métier, IT et fournisseurs.", "Un pilotage fondé sur l’activité plutôt que sur les résultats.", "Des données dispersées entre Jira, Confluence, Excel et les outils PPM."];
const outcomes = ["Des engagements plus explicites", "Des dépendances visibles", "Des arbitrages plus rapides", "Des risques détectés plus tôt", "Une meilleure prévisibilité", "Moins de reporting manuel", "Des données de delivery mieux exploitées", "Un management concentré sur les décisions"];
const faqs = [
  ["NEATCH est-il une agence ou une ESN ?", "Non. Je pilote personnellement les interventions NEATCH. Selon les besoins du programme, je réunis et j’organise des consultants d’ESN et des freelances issus de Malt, d’autres plateformes ou de mon réseau. Je clarifie leurs responsabilités, coordonne leurs contributions et structure un cadre de delivery commun."],
  ["Comment travaillez-vous avec les ESN et les plateformes de freelances ?", "Je m’appuie sur cet écosystème pour identifier les compétences adaptées au programme. Je qualifie les profils en fonction du contexte, puis j’organise leur contribution avec les équipes métier et IT. Les ESN, Malt et les autres plateformes restent des partenaires du dispositif."],
  ["Quand faire appel à NEATCH ?", "Lorsque votre programme implique plusieurs équipes et fournisseurs, des responsabilités fragmentées et des dépendances difficiles à piloter. Nous intervenons auprès des grandes entreprises et ETI pour structurer une capacité de delivery alignée avec les objectifs métier."],
  ["Quel est votre périmètre d’intervention ?", "La gouvernance, l’architecture du delivery et la transformation de l’organisation : responsabilités, capacités, dépendances, engagements, risques et arbitrages. Nous travaillons avec les équipes métier, IT, architecture et les intégrateurs."],
  ["Quelle place donnez-vous à l’IA ?", "L’IA est intégrée progressivement pour consolider le reporting, exploiter la connaissance projet, repérer les risques et préparer les décisions. Les usages dépendent de la qualité des données, des droits d’accès et des règles de confidentialité. Les décisions restent sous responsabilité humaine."],
  ["Comment démarre une collaboration ?", "Un premier échange permet de comprendre vos objectifs, vos acteurs, vos contraintes et les points de friction. Nous définissons ensuite un diagnostic, un périmètre d’intervention et des résultats attendus, avec des indicateurs adaptés au contexte."]
];
function Heading({ number, label, title, children }: { number: string; label: string; title: string; children?: React.ReactNode }) {
  return <div className="section-head"><div><span className="mono muted">{number} / {label}</span><h2>{title}</h2></div>{children && <p>{children}</p>}</div>;
}
export default function EditorialHome() {
  return <div className="editorial-site light">
    <header><nav className="wrap" aria-label="Navigation principale"><a href="#main-content" aria-label="NEATCH, accueil"><Image className="logo" src="/neatch-logo-wordmark.png" alt="NEATCH" width={119} height={31} priority /></a><div className="nav-links">{links.map(([href, label]) => <a key={href} href={href}>{label}</a>)}</div><details className="mobile-menu"><summary>Menu ＋</summary><div>{links.map(([href, label]) => <a href={href} key={href}>{label}</a>)}</div></details></nav></header>
    <main id="main-content" tabIndex={-1}>
      <section className="hero" aria-labelledby="hero-title"><div className="wrap"><div className="hero-inner"><div><p className="eyebrow mono">Transformation &amp; Delivery</p><h1 id="hero-title">Piloter les transformations complexes.<br /><span>Livrer ce qui compte.</span></h1><p className="intro">NEATCH prend en charge la gouvernance et le delivery de programmes de transformation complexes mêlant ERP, data, IA, intégration, équipes multiples et fournisseurs multiples.</p><p className="intro">Nous transformons la coordination en un système de delivery mesurable, prévisible et progressivement automatisé.</p><div className="actions"><a className="primary" href="#contact">Discuter d’un programme <span aria-hidden="true">↗</span></a><a className="text-link" href="#methode">Découvrir notre approche ↓</a></div></div><aside className="delivery-note" aria-label="Principes du système de delivery"><span className="mono">Du programme au système</span><p className="note-title">Une ambition.<br />Des engagements.<br /><em>Un système pilotable.</em></p><div className="note-rows">{["Responsabilités clarifiées", "Dépendances visibles", "Décisions documentées", "Résultats mesurables"].map((item, index) => <div key={item}><span className="mono">0{index + 1}</span><span>{item}</span></div>)}</div><p className="note-foot">Métier · IT · Équipes · Fournisseurs</p></aside></div><div className="hero-bottom"><span>Gouvernance · Transformation · Delivery</span><span>Pour les DSI, CTO et directions de programme</span></div></div></section>
      <section className="clients" aria-label="Références du parcours de Lionel Sultan"><div className="wrap"><p className="mono muted">Des expériences dans des organisations exigeantes</p><ul className="clients-grid"><li>Dior</li><li>CHANEL</li><li>EDF Renouvelables</li><li>BNP PARIBAS</li></ul></div></section>
      <section className="section wrap" id="enjeux"><Heading number="01" label="Le constat" title="Quand le programme devient plus complexe que son organisation">Les équipes travaillent. Les réunions s’enchaînent. Mais la trajectoire et la capacité à livrer restent difficiles à lire.</Heading><ul className="problem-grid">{problems.map((item, index) => <li key={item}><span className="mono muted">0{index + 1}</span><p>{item}</p></li>)}</ul><p className="statement">Le problème n’est généralement pas le manque d’activité. C’est l’absence d’un système de delivery suffisamment clair pour transformer cette activité en résultats prévisibles.</p></section>
      <section className="section tinted" id="principes"><div className="wrap"><Heading number="02" label="Notre proposition" title="Construire un véritable système de delivery">Transformer les organisations qui produisent beaucoup de coordination et de temps passé en systèmes de delivery mesurables, automatisés et pilotés par les résultats.</Heading><div className="pillar-grid">{pillars.map(([title, text], index) => <article key={title}><span className="mono muted">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section wrap" id="expertise"><Heading number="03" label="Expertise" title="Là où organisation, technologie et delivery se rencontrent">Relier les enjeux métier à la réalité des systèmes, des équipes et des fournisseurs. Notre rôle : la gouvernance, l’architecture du delivery et la transformation.</Heading><ul className="expertise-grid">{["Program Delivery", "Transformation Operating Model", "ERP / SAP", "Supply Chain", "Data & Analytics", "Integration & APIs", "Cloud", "AI-enabled Delivery", "Product & Portfolio Governance"].map(item => <li key={item}>{item}<span aria-hidden="true">↗</span></li>)}</ul><p className="section-note">SAP transformation, data transformation, integration governance, supply chain transformation : des contextes différents, une même exigence de pilotage transverse.</p></section>
      <section className="section tinted" id="methode"><div className="wrap"><Heading number="04" label="Approach" title="De la situation complexe au système pilotable">Un delivery operating model adapté à votre programme, puis mis en œuvre avec les équipes.</Heading><div className="method-grid">{steps.map(([title, text], index) => <article key={title}><span className="mono muted">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section wrap" id="ai-delivery"><Heading number="05" label="AI-enabled Delivery" title="L’IA, une couche opérationnelle du delivery">Synthèse automatique, analyse des risques, préparation de décisions, détection de dépendances, génération de reporting et exploitation de la connaissance projet.</Heading><div className="ai-grid">{[["Automate reporting", "Consolider les données Jira, Confluence et PPM, synthétiser l’avancement et générer les supports de pilotage."], ["Surface risks and dependencies", "Faire émerger les signaux de risque, repérer les dépendances et exploiter la connaissance projet."], ["Augment decision-making", "Préparer les arbitrages, rendre les options lisibles et documenter les éléments utiles à la décision."]].map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><p className="section-note">Une automatisation progressive, selon la qualité des sources, les droits d’accès et les règles de confidentialité du programme.</p></section>
      <section className="section results" id="resultats"><div className="wrap"><Heading number="06" label="Résultats attendus" title="Ce que doit produire une intervention NEATCH">Des changements observables dans la façon de piloter et de livrer. Les indicateurs et leur point de départ sont définis avec vous.</Heading><ul className="outcome-grid">{outcomes.map(item => <li key={item}><span aria-hidden="true">↗</span>{item}</li>)}</ul></div></section>
      <section className="section wrap" id="about"><div className="about-grid"><div><Heading number="07" label="About" title="Un cabinet indépendant. Une expérience de terrain." /><p className="intro">NEATCH est ma structure indépendante pour piloter la gouvernance et le delivery de transformations complexes.</p><p>Je ne suis pas une agence. Je réunis et j’organise les compétences nécessaires au programme : consultants d’ESN, freelances issus de Malt et d’autres plateformes, ainsi que de mon réseau.</p><p>Je reste votre interlocuteur pour qualifier les profils, clarifier les responsabilités et organiser leurs contributions dans un système de delivery commun.</p><p>Nous intervenons au croisement du métier, de l’IT, de l’architecture et des équipes de delivery pour transformer des programmes complexes en systèmes pilotables.</p><p>Nous travaillons avec les DSI, CIO, CTO, directions de programme et de transformation, responsables ERP, Data et Digital et directions Supply Chain et Operations.</p><p className="section-note">Program Delivery Lead · Transformation Lead · Product &amp; Delivery Lead · Program Governance</p></div><figure className="founder"><Image src="/lionel-sultan.png" alt="Lionel Sultan, fondateur de NEATCH" width={480} height={480} sizes="(max-width: 760px) 88vw, 360px" /><figcaption><strong>Lionel Sultan</strong><span>Fondateur · 15 ans d’expérience</span></figcaption></figure></div></section>
      <section className="section tinted" id="references"><div className="wrap"><Heading number="08" label="Références" title="Des programmes ancrés dans la réalité des organisations">Une sélection issue du parcours de Lionel Sultan, du luxe à l’énergie et aux services financiers.</Heading><div className="reference-highlights"><article><span className="mono muted">Luxe · Supply Chain</span><h3>Christian Dior Couture</h3><p>Orchestration du delivery multi-équipes, Product Management sur Merchandise Planning et pilotage d’un projet supply chain basé sur Anaplan.</p></article><article><span className="mono muted">Énergie · Systèmes métier</span><h3>EDF Renouvelables</h3><p>Pilotage de projets métier et terrain, évolutions d’une application de maintenance SAP et coordination de chantiers applicatifs et infrastructures.</p></article></div><details className="reference-library"><summary>Explorer toutes les références du parcours</summary><div>{references.map(reference => <details className="reference-entry" key={`${reference.company}-${reference.period}`}><summary><strong>{reference.company}</strong><span>{reference.period}</span></summary><h3>{reference.role}</h3><p>{reference.context}</p><div className="reference-columns"><div><h4>Travaux clés</h4><ul>{reference.assignments.map(item => <li key={item}>{item}</li>)}</ul></div><div><h4>Résultats de la mission</h4><ul>{reference.outcomes.map(item => <li key={item}>{item}</li>)}</ul></div></div></details>)}</div></details></div></section>
      <section id="faq" className="section wrap"><Heading number="09" label="Questions fréquentes" title="Préciser le cadre d’intervention" /><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
      <section className="contact wrap" id="contact"><div className="contact-box"><div><span className="mono">Discuter d’un programme</span><h2>Votre transformation mérite<br />un système de delivery clair.</h2><p>Un premier échange pour comprendre vos objectifs, vos dépendances et les décisions à sécuriser.</p></div><div className="contact-links"><a className="primary" href="mailto:contact@neatch.com">Discuter d’un programme ↗</a><a className="text-link" href="mailto:contact@neatch.com">contact@neatch.com</a><a className="text-link" href="https://www.linkedin.com/in/lionelsultan" target="_blank" rel="noopener noreferrer">Lionel Sultan sur LinkedIn ↗<span className="sr-only"> (nouvel onglet)</span></a></div></div></section>
    </main><footer><div className="wrap"><a href="#main-content" aria-label="NEATCH, retour en haut"><Image className="logo" src="/neatch-logo-wordmark.png" alt="NEATCH" width={119} height={31} /></a><span>© 2026 NEATCH · Transformation &amp; Delivery</span><a href="#faq">Questions fréquentes</a><a href="/legal">Mentions légales ↗</a></div></footer>
  </div>;
}
